services:
  api:
    image: corstestapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CorsTestApi
    ports:
      - 40215:5000
      - 40214:5001
    user: "root:root"
    volumes:
      - ./data/:/app/db
      - ~/.aspnet/https:/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Production