services:
  api:
    image: corstestapi:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CorsTestApi
    ports:
      - 80
      - 443
    user: "root:root"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production