services:
  temperaturapp:
    image: corstestfront:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CorsTestFront
    ports:
      - "6602:80"
    user: "root:root"
    restart: always